### ISSUE TITLE
Markers moving away from point while map is being dragged

### ISSUE THREAD

**Issue by flavioarfaria** [cyrilmottier/Polaris#16]
How to reproduce:

1) Zoom in towards a marker;
2) While the new tiles are loading and you still get interpolated, scaled up tiles, move the map away from the marker you're zooming in.

This is what will happen:

http://img266.imageshack.us/img266/5526/device20121026092905.png

The blue marker was supposed to be over Los Angeles. After finish loading the tiles for that zoom level, everything is fine. This is the demo app downloaded from Google play.

**Comment by cyrilmottier** [comment]
This is actually a bug from the `MapView` which uses `integer`s instead of `double`s. Hence when computing locations while zooming in/out the result doesn't have a great precision which results in having tiles drawn at the incorrect position.

Once again, I think I won't be able to fix that as it's due to the Google Maps external library :(.

**Comment by cyrilmottier** [comment]
Bug related to the Google Maps external library and that can't be solved Polaris. Closing
